# Generated by Django 2.0.3 on 2018-04-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
