# Generated by Django 2.0.1 on 2018-02-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_auto_20180222_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('generated_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_case', to='case.case')),
                ('lab_attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_lab_attendant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
