# Generated by Django 2.0.3 on 2018-04-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='requested_date',
        ),
    ]
